import type { Metadata } from "next";
import { Pacifico, Poppins, Libre_Franklin, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

const pacifico_init = Pacifico({
  variable: "--font-pacifico",
  weight:"400",
  subsets: ["latin"],
});


const playfair_display_init  = Playfair_Display({
variable: "--font-playfair-display",
  weight:["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const Libre_Franklin_init = Libre_Franklin({
variable: "--font-libre-franklin",
  weight:["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const Poppins_init = Poppins({
  variable: "--font-poppins",
  weight:["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pacifico_init.variable} ${Poppins_init.variable} ${Libre_Franklin_init.variable}  ${playfair_display_init.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
